add LocalGravity AG and LEAP description
elixir-cn/elixir-china-companies pull request #9
Opened 2017-02-07 09:45 UTC by weij

2017-02-07 09:52 UTC, tony612 requested changes

2017-02-07 09:52 UTC, tony612 commented on README.md
> +  [LEAP] - 企业级零售数据分析平台。采用Elixir, Phoenix, Postgres, Docker实现API server。
这个没有链接吗？ 没有的话，直接写成 `LEAP` 吧。 另外，这段最好和上一段放在一起吧。

2017-02-07 09:52 UTC, tony612 commented on README.md
> +* [LocalGravity AG](http://www.linkedin.com/company/localgravity?trk=top_nav_home) - 是一家零售数据选址咨询服务公司，成立于2012年，服务遍布中国、亚洲市场，中国分部有约135位员工。其拥有经验丰富的，结合本土与国际的专家团队，通过采集原始数据、建立零售地理信息平台、提供选址分析咨询服务; 协助连锁企业以科学的
为什么不直接贴公司官网呢？ http://www.localgravity.com/

2017-02-08 01:53 UTC, weij commented on README.md
> +* [LocalGravity AG](http://www.linkedin.com/company/localgravity?trk=top_nav_home) - 是一家零售数据选址咨询服务公司，成立于2012年，服务遍布中国、亚洲市场，中国分部有约135位员工。其拥有经验丰富的，结合本土与国际的专家团队，通过采集原始数据、建立零售地理信息平台、提供选址分析咨询服务; 协助连锁企业以科学的
也可以

2017-02-08 01:53 UTC, weij commented on README.md
> +  [LEAP] - 企业级零售数据分析平台。采用Elixir, Phoenix, Postgres, Docker实现API server。
稍后更改完您再看看

2017-02-08 02:03 UTC, weij commented
修改为链接官网

2017-02-08 02:44 UTC, merged